INSERT INTO COZINHA (ID, NOME) VALUES (1, 'Tailandesa');
INSERT INTO COZINHA (ID, NOME) VALUES (2, 'Indiana');

INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Mangai', 10, 1);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Nau', 9.50, 1);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Tuk Tuk Comida Indiana', 15, 2);